# AUTO-GENERATED by scripts/generate-python-client.ts — DO NOT EDIT BY HAND.
# Regenerate with: bun run scripts/generate-python-client.ts
# ruff: noqa

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class AskAgentProjectPodcastRelevancySearchOptionsVariant1Project(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_id: str = Field(alias="projectId")
    exclude_ignored_podcasts: bool | None = Field(default=None, alias="excludeIgnoredPodcasts")
    exclude_podcasts_on_list: bool | None = Field(default=None, alias="excludePodcastsOnList")
    include_podcast_relevancy: bool | None = Field(default=None, alias="includePodcastRelevancy")
    exclude_relvancy_values: list[float] | None = Field(default=None, alias="excludeRelvancyValues")
    force_recalculate_relevancy: bool | None = Field(default=None, alias="forceRecalculateRelevancy")


class AskAgentProjectPodcastRelevancySearchOptionsVariant1SearchTermsItemSearchTermOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    match_mode: Literal["must", "not", "optional"] = Field(alias="matchMode")
    phrase_match: bool | None = Field(default=None, alias="phraseMatch")
    slop: float | None = None
    fuzzy: bool | None = None


class AskAgentProjectPodcastRelevancySearchOptionsVariant1SearchTermsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    search_term: str = Field(alias="searchTerm")
    search_type: Literal["text", "embeddings"] = Field(alias="searchType")
    search_targets: list[Literal["podcast-title", "podcast-description"]] = Field(alias="searchTargets")
    search_term_options: AskAgentProjectPodcastRelevancySearchOptionsVariant1SearchTermsItemSearchTermOptions = Field(
        alias="searchTermOptions"
    )


class AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScoreAuthorityScore(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    min: float | None
    max: float | None


class AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScore(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    authority_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScoreAuthorityScore | None = (
        Field(default=None, alias="authorityScore")
    )
    quality_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScoreAuthorityScore | None = (
        Field(default=None, alias="qualityScore")
    )
    engagement_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScoreAuthorityScore | None = (
        Field(default=None, alias="engagementScore")
    )
    social_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScoreAuthorityScore | None = (
        Field(default=None, alias="socialScore")
    )
    youtube_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScoreAuthorityScore | None = (
        Field(default=None, alias="youtubeScore")
    )


class AskAgentProjectPodcastRelevancySearchOptionsVariant1SortOrderItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    field: Literal["relevance", "recentActivity", "title", "appleReviews", "spotifyReviews"]
    direction: Literal["asc", "desc"] | None = None
    null_order: Literal["first", "last"] | None = Field(default=None, alias="nullOrder")


class AskAgentProjectPodcastRelevancySearchOptionsVariant1(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    cursor: str | None = None
    page_size: int | None = Field(default=None, alias="pageSize")
    project: AskAgentProjectPodcastRelevancySearchOptionsVariant1Project | None = None
    project_id: str | None = Field(default=None, alias="projectId")
    search_terms: list[AskAgentProjectPodcastRelevancySearchOptionsVariant1SearchTermsItem] | None = Field(
        default=None, alias="searchTerms"
    )
    exclude_itunes_genres: list[str] | None = Field(default=None, alias="excludeItunesGenres")
    exclude_podcast_ids: list[str] | None = Field(default=None, alias="excludePodcastIds")
    exclude_episode_ids: list[str] | None = Field(default=None, alias="excludeEpisodeIds")
    explicit: Literal["clean", "explicit"] | None = None
    founded_since: Any | None = Field(default=None, alias="foundedSince")
    has_primary_contact: bool | None = Field(default=None, alias="hasPrimaryContact")
    has_socials: (
        list[
            Literal[
                "beehiiv",
                "behance",
                "bluesky",
                "discord",
                "facebook",
                "github",
                "instagram",
                "linkedin",
                "linktree",
                "mastodon",
                "medium",
                "patreon",
                "pinterest",
                "reddit",
                "snapchat",
                "soundcloud",
                "substack",
                "threads",
                "tiktok",
                "tumblr",
                "twitch",
                "twitter",
                "vimeo",
                "whatsapp",
                "youtube",
            ]
        ]
        | None
    ) = Field(default=None, alias="hasSocials")
    include_itunes_genres: list[str] | None = Field(default=None, alias="includeItunesGenres")
    include_podcast_ids: list[str] | None = Field(default=None, alias="includePodcastIds")
    languages: list[str] | None = None
    last_episode_date_since: Any | None = Field(default=None, alias="lastEpisodeDateSince")
    max_total_episodes: int | None = Field(default=None, alias="maxTotalEpisodes")
    min_castbox_plays: int | None = Field(default=None, alias="minCastboxPlays")
    min_castbox_subscribers: int | None = Field(default=None, alias="minCastboxSubscribers")
    min_itunes_rating: float | None = Field(default=None, alias="minItunesRating")
    min_itunes_rating_count: int | None = Field(default=None, alias="minItunesRatingCount")
    min_spotify_rating: float | None = Field(default=None, alias="minSpotifyRating")
    min_spotify_rating_count: int | None = Field(default=None, alias="minSpotifyRatingCount")
    min_total_episodes: int | None = Field(default=None, alias="minTotalEpisodes")
    podcast_countries: list[str] | None = Field(default=None, alias="podcastCountries")
    podcast_has_guests: bool | None = Field(default=None, alias="podcastHasGuests")
    podcast_authority_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScore | None = Field(
        default=None, alias="podcastAuthorityScore"
    )
    sort_order: list[AskAgentProjectPodcastRelevancySearchOptionsVariant1SortOrderItem] | None = Field(
        default=None, alias="sortOrder"
    )


class AskAgentProjectPodcastRelevancySearchOptionsVariant2SearchTermsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    search_term: str = Field(alias="searchTerm")
    search_type: Literal["text", "embeddings"] = Field(alias="searchType")
    search_targets: list[
        Literal["podcast-title", "podcast-description", "episode-title", "episode-description", "transcript"]
    ] = Field(alias="searchTargets")
    search_term_options: AskAgentProjectPodcastRelevancySearchOptionsVariant1SearchTermsItemSearchTermOptions = Field(
        alias="searchTermOptions"
    )


class AskAgentProjectPodcastRelevancySearchOptionsVariant2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    cursor: str | None = None
    page_size: int | None = Field(default=None, alias="pageSize")
    project: AskAgentProjectPodcastRelevancySearchOptionsVariant1Project | None = None
    project_id: str | None = Field(default=None, alias="projectId")
    search_terms: list[AskAgentProjectPodcastRelevancySearchOptionsVariant2SearchTermsItem] | None = Field(
        default=None, alias="searchTerms"
    )
    exclude_itunes_genres: list[str] | None = Field(default=None, alias="excludeItunesGenres")
    exclude_podcast_ids: list[str] | None = Field(default=None, alias="excludePodcastIds")
    exclude_episode_ids: list[str] | None = Field(default=None, alias="excludeEpisodeIds")
    explicit: Literal["clean", "explicit"] | None = None
    founded_since: Any | None = Field(default=None, alias="foundedSince")
    has_primary_contact: bool | None = Field(default=None, alias="hasPrimaryContact")
    has_socials: (
        list[
            Literal[
                "beehiiv",
                "behance",
                "bluesky",
                "discord",
                "facebook",
                "github",
                "instagram",
                "linkedin",
                "linktree",
                "mastodon",
                "medium",
                "patreon",
                "pinterest",
                "reddit",
                "snapchat",
                "soundcloud",
                "substack",
                "threads",
                "tiktok",
                "tumblr",
                "twitch",
                "twitter",
                "vimeo",
                "whatsapp",
                "youtube",
            ]
        ]
        | None
    ) = Field(default=None, alias="hasSocials")
    include_itunes_genres: list[str] | None = Field(default=None, alias="includeItunesGenres")
    include_podcast_ids: list[str] | None = Field(default=None, alias="includePodcastIds")
    languages: list[str] | None = None
    last_episode_date_since: Any | None = Field(default=None, alias="lastEpisodeDateSince")
    max_total_episodes: int | None = Field(default=None, alias="maxTotalEpisodes")
    min_castbox_plays: int | None = Field(default=None, alias="minCastboxPlays")
    min_castbox_subscribers: int | None = Field(default=None, alias="minCastboxSubscribers")
    min_itunes_rating: float | None = Field(default=None, alias="minItunesRating")
    min_itunes_rating_count: int | None = Field(default=None, alias="minItunesRatingCount")
    min_spotify_rating: float | None = Field(default=None, alias="minSpotifyRating")
    min_spotify_rating_count: int | None = Field(default=None, alias="minSpotifyRatingCount")
    min_total_episodes: int | None = Field(default=None, alias="minTotalEpisodes")
    podcast_countries: list[str] | None = Field(default=None, alias="podcastCountries")
    podcast_has_guests: bool | None = Field(default=None, alias="podcastHasGuests")
    podcast_authority_score: AskAgentProjectPodcastRelevancySearchOptionsVariant1PodcastAuthorityScore | None = Field(
        default=None, alias="podcastAuthorityScore"
    )
    sort_order: list[AskAgentProjectPodcastRelevancySearchOptionsVariant1SortOrderItem] | None = Field(
        default=None, alias="sortOrder"
    )
    include_transcript_snippet: bool | None = Field(default=None, alias="includeTranscriptSnippet")
    transcript_snippet_length: int | None = Field(default=None, alias="transcriptSnippetLength")
    transcript_highlight_length: int | None = Field(default=None, alias="transcriptHighlightLength")
    include_episode_ids: list[str] | None = Field(default=None, alias="includeEpisodeIds")
    published_since: Any | None = Field(default=None, alias="publishedSince")
    has_transcript: bool | None = Field(default=None, alias="hasTranscript")
    episode_updated_since: Any | None = Field(default=None, alias="episodeUpdatedSince")
    episode_created_since: Any | None = Field(default=None, alias="episodeCreatedSince")


class AskAgentProjectPodcastRelevancyResponseResultAnswer(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    rating: int
    justification: str
    strengths: Any
    concerns: Any


class AskAgentProjectPodcastRelevancyResponseResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    answer: AskAgentProjectPodcastRelevancyResponseResultAnswer


class AskAgentProjectPodcastRelevancyResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    result: AskAgentProjectPodcastRelevancyResponseResult


class GetAlternativeSpellingsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    spellings: list[str]


class CreateAlertConfigEmailSettings(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    frequency: Literal["hourly", "daily", "weekly"]


class CreateAlertConfigAdditionalAlertSettings(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    other_emails: list[str] | None = Field(default=None, alias="otherEmails")
    other_spellings: list[str] | None = Field(default=None, alias="otherSpellings")


class CreateAlertConfigResponseCreatedAlertConfig(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    created_by_user_id: str = Field(alias="createdByUserId")
    team_id: str = Field(alias="teamId")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    alert_name: str = Field(alias="alertName")
    alert_type: Literal["person", "company", "custom-keyword"] = Field(alias="alertType")
    enabled: bool
    alert_settings: Any = Field(alias="alertSettings")
    email_settings: CreateAlertConfigEmailSettings = Field(alias="emailSettings")
    last_run_date: Any | None = Field(alias="lastRunDate")


class CreateAlertConfigResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    created_alert_config: CreateAlertConfigResponseCreatedAlertConfig = Field(alias="createdAlertConfig")


class GetAlertConfigsResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    enabled: bool | None = None
    alert_config_id: str | None = Field(default=None, alias="alertConfigId")
    sort_by: Literal["lastRunDate", "alertName"] | None = Field(default=None, alias="sortBy")
    sort_direction: Literal["asc", "desc"] | None = Field(default=None, alias="sortDirection")


class GetAlertConfigsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetAlertConfigsResponseOptions
    alert_configs: list[CreateAlertConfigResponseCreatedAlertConfig] = Field(alias="alertConfigs")


class GetAlertConfigResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    alert_config: CreateAlertConfigResponseCreatedAlertConfig = Field(alias="alertConfig")


class UpdateAlertConfigUpdates(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    alert_name: str | None = Field(default=None, alias="alertName")
    email_settings: CreateAlertConfigEmailSettings | None = Field(default=None, alias="emailSettings")
    alert_settings: Any | None = Field(default=None, alias="alertSettings")
    enabled: bool | None = None


class UpdateAlertConfigResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    updated_alert_config: CreateAlertConfigResponseCreatedAlertConfig = Field(alias="updatedAlertConfig")


class DeleteAlertConfigResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    deleted_alert_config_id: str = Field(alias="deletedAlertConfigId")


class GetAlertMatchHistoryResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    alert_config_id: str | None = Field(default=None, alias="alertConfigId")
    page: float | None = None
    since_date: Any | None = Field(default=None, alias="sinceDate")


class GetAlertMatchHistoryResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetAlertMatchHistoryResponseOptions
    total_alert_matches: float = Field(alias="totalAlertMatches")
    alert_matches: list[Any] = Field(alias="alertMatches")


class GetChartResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    chart_type: Literal["apple", "spotify"] | None = Field(default=None, alias="chartType")
    category: str | None = None
    country: str | None = None
    positions_limit: float | None = Field(default=None, alias="positionsLimit")
    date: str | None = None


class GetChartResponseChartChart(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    chart_type: Literal["apple", "spotify"] = Field(alias="chartType")
    category: str
    country: str
    chart_date: str = Field(alias="chartDate")


class GetChartResponseChartPositionsItemPodcastOnChart(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_on_chart_id: str = Field(alias="podcastOnChartId")
    title: str
    image_url: str | None = Field(alias="imageUrl")


class GetChartResponseChartPositionsItemPodenginePodcastAuthorityScore(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    calculated_at: Any = Field(alias="calculatedAt")
    authority_score: float = Field(alias="authorityScore")
    quality_score: float = Field(alias="qualityScore")
    youtube_score: float = Field(alias="youtubeScore")
    social_score: float = Field(alias="socialScore")
    engagement_score: float = Field(alias="engagementScore")


class GetChartResponseChartPositionsItemPodenginePodcast(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    author: str | None
    authority_score: GetChartResponseChartPositionsItemPodenginePodcastAuthorityScore | None = Field(
        alias="authorityScore"
    )
    genres: list[str]
    id: str
    image_url: str | None = Field(alias="imageUrl")
    language: str
    last_episode_published_at: Any = Field(alias="lastEpisodePublishedAt")
    slug: str
    title: str
    title_latest: str = Field(alias="titleLatest")


class GetChartResponseChartPositionsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    position: float
    podcast_on_chart: GetChartResponseChartPositionsItemPodcastOnChart = Field(alias="podcastOnChart")
    podengine_podcast: GetChartResponseChartPositionsItemPodenginePodcast | None = Field(alias="podenginePodcast")


class GetChartResponseChart(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    chart: GetChartResponseChartChart
    positions: list[GetChartResponseChartPositionsItem]


class GetChartResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetChartResponseOptions
    chart: GetChartResponseChart | None


class GetLatestChartResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    chart_type: Literal["apple", "spotify"] | None = Field(default=None, alias="chartType")
    category: str | None = None
    country: str | None = None
    positions_limit: float | None = Field(default=None, alias="positionsLimit")


class GetLatestChartResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetLatestChartResponseOptions
    chart: GetChartResponseChart | None


class GetCategoriesByChartTypeResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    categories: list[str]


class GetAvailableCountriesByChartTypeResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    countries: list[str]


class GetLatestEpisodesResponseLatestPodcastsItemPodcast(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    author: str | None
    authority_score: GetChartResponseChartPositionsItemPodenginePodcastAuthorityScore | None = Field(
        alias="authorityScore"
    )
    genres: list[str]
    id: str
    image_url: str | None = Field(alias="imageUrl")
    language: str
    last_episode_published_at: Any = Field(alias="lastEpisodePublishedAt")
    slug: str
    title: str
    title_latest: str = Field(alias="titleLatest")


class GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemEpisodeGuestsAndHostsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    name: str
    type: Literal["host", "guest", "unknown", "mentioned"]
    image_url: str | None = Field(alias="imageUrl")


class GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemAudienceEstimateAudienceDemographics(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    age_range: Literal["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"] = Field(alias="ageRange")
    gender_skew: Literal[
        "Male 0% Female 100%",
        "Male 20% Female 80%",
        "Male 40% Female 60%",
        "Male 50% Female 50%",
        "Male 60% Female 40%",
        "Male 80% Female 20%",
        "Male 100% Female 0%",
    ] = Field(alias="genderSkew")
    education_level: Literal[
        "No High School", "High School", "Some College", "Bachelors Degree", "Masters Degree", "Doctorate"
    ] = Field(alias="educationLevel")
    income_level: Literal[
        "Under $25K", "$25K-$50K", "$50K-$75K", "$75K-$100K", "$100K-$150K", "$150K-$200K", "$200K+"
    ] = Field(alias="incomeLevel")
    example_listener_profile: str = Field(alias="exampleListenerProfile")


class GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemAudienceEstimate(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    audience_demographics: (
        GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemAudienceEstimateAudienceDemographics | None
    ) = Field(alias="audienceDemographics")
    estimated_monthly_listeners: float | None = Field(alias="estimatedMonthlyListeners")
    estimated_monthy_listeners_calculated_at: Any | None = Field(alias="estimatedMonthyListenersCalculatedAt")


class GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemYoutubeEpisodeDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    youtube_link: str = Field(alias="youtubeLink")
    youtube_match_confidence: float = Field(alias="youtubeMatchConfidence")
    youtube_view_count: float | None = Field(alias="youtubeViewCount")
    youtube_data_fetched_at: Any | None = Field(alias="youtubeDataFetchedAt")


class GetLatestEpisodesResponseLatestPodcastsItemEpisodesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    deep_analysis_requested_at: Any | None = Field(alias="deepAnalysisRequestedAt")
    description: str | None
    duration_seconds: float | None = Field(alias="durationSeconds")
    enclosure_url: str = Field(alias="enclosureUrl")
    episode_id: str = Field(alias="episodeId")
    episode_guests_and_hosts: (
        list[GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemEpisodeGuestsAndHostsItem] | None
    ) = Field(alias="episodeGuestsAndHosts")
    episode_slug: str = Field(alias="episodeSlug")
    episode_short_description: str | None = Field(alias="episodeShortDescription")
    episode_sponsors: list[str] | None = Field(alias="episodeSponsors")
    has_transcript: bool = Field(alias="hasTranscript")
    has_video: bool = Field(alias="hasVideo")
    video_url: str | None = Field(alias="videoUrl")
    image_url: str | None = Field(alias="imageUrl")
    episode_thumbnail_rss_url: str | None = Field(alias="episodeThumbnailRssUrl")
    podcast_id: str = Field(alias="podcastId")
    podcast_slug: str = Field(alias="podcastSlug")
    published_at: Any = Field(alias="publishedAt")
    title: str
    transcript_id: str | None = Field(alias="transcriptId")
    transcription_requested_at: Any | None = Field(alias="transcriptionRequestedAt")
    audience_estimate: GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemAudienceEstimate | None = Field(
        default=None, alias="audienceEstimate"
    )
    youtube_episode_details: GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemYoutubeEpisodeDetails | None = (
        Field(alias="youtubeEpisodeDetails")
    )
    apple_podcasts_url: str | None = Field(alias="applePodcastsUrl")


class GetLatestEpisodesResponseLatestPodcastsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    episodes: list[GetLatestEpisodesResponseLatestPodcastsItemEpisodesItem]


class GetLatestEpisodesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    latest_podcasts: list[GetLatestEpisodesResponseLatestPodcastsItem] = Field(alias="latestPodcasts")


class GetEpisodeDetailsByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    episode: GetLatestEpisodesResponseLatestPodcastsItemEpisodesItem


class GetEpisodeTranscriptTextResponseEpisodeTranscriptText(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    episode_id: str = Field(alias="episodeId")
    transcript_id: str = Field(alias="transcriptId")
    text: str | None


class GetEpisodeTranscriptTextResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    episode_transcript_text: GetEpisodeTranscriptTextResponseEpisodeTranscriptText = Field(
        alias="episodeTranscriptText"
    )


class RequestEpisodeTranscriptionResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    message: str


class GetEpisodeTranscriptTimestampsResponseSentencesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    text: str
    start_second: float = Field(alias="startSecond")
    end_second: float = Field(alias="endSecond")


class GetEpisodeTranscriptTimestampsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    episode_id: str = Field(alias="episodeId")
    podcast_id: str = Field(alias="podcastId")
    sentences: list[GetEpisodeTranscriptTimestampsResponseSentencesItem]


class GetTranscriptionRequestsResponseRequestsItemVariant1(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_title: str = Field(alias="podcastTitle")
    podcast_image_url: str | None = Field(alias="podcastImageUrl")
    podcast_id: str = Field(alias="podcastId")
    podcast_slug: str = Field(alias="podcastSlug")
    requested_at: Any = Field(alias="requestedAt")
    requested_by_user_id: str | None = Field(alias="requestedByUserId")
    completed_at: Any | None = Field(alias="completedAt")
    request_type: Literal["transcription", "deepAnalysis", "diarization"] = Field(alias="requestType")
    episode_id: str = Field(alias="episodeId")
    episode_title: str | None = Field(alias="episodeTitle")
    episode_image_url: str | None = Field(alias="episodeImageUrl")
    episode_slug: str = Field(alias="episodeSlug")


class GetTranscriptionRequestsResponseRequestsItemVariant2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_title: str = Field(alias="podcastTitle")
    podcast_image_url: str | None = Field(alias="podcastImageUrl")
    podcast_id: str = Field(alias="podcastId")
    podcast_slug: str = Field(alias="podcastSlug")
    requested_at: Any = Field(alias="requestedAt")
    requested_by_user_id: str | None = Field(alias="requestedByUserId")
    completed_at: Any | None = Field(alias="completedAt")
    request_type: Literal["guestPrep"] = Field(alias="requestType")
    episode_id: Any | None = Field(alias="episodeId")
    episode_title: Any | None = Field(alias="episodeTitle")
    episode_image_url: Any | None = Field(alias="episodeImageUrl")
    episode_slug: Any | None = Field(alias="episodeSlug")


class GetTranscriptionRequestsResponseRequestsItemVariant3(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_title: str = Field(alias="podcastTitle")
    podcast_image_url: str | None = Field(alias="podcastImageUrl")
    podcast_id: str = Field(alias="podcastId")
    podcast_slug: str = Field(alias="podcastSlug")
    requested_at: Any = Field(alias="requestedAt")
    requested_by_user_id: str | None = Field(alias="requestedByUserId")
    completed_at: Any | None = Field(alias="completedAt")
    request_type: Literal["autoOutreach"] = Field(alias="requestType")
    episode_id: Any | None = Field(alias="episodeId")
    episode_title: Any | None = Field(alias="episodeTitle")
    episode_image_url: Any | None = Field(alias="episodeImageUrl")
    episode_slug: Any | None = Field(alias="episodeSlug")


class GetTranscriptionRequestsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total_requests: float = Field(alias="totalRequests")
    requests: list[
        GetTranscriptionRequestsResponseRequestsItemVariant1
        | GetTranscriptionRequestsResponseRequestsItemVariant2
        | GetTranscriptionRequestsResponseRequestsItemVariant3
    ]


class CreateGuestProfileResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    guest_profile_id: str = Field(alias="guestProfileId")
    guest_profile_slug: str = Field(alias="guestProfileSlug")
    project_id: str = Field(alias="projectId")
    project_slug: str = Field(alias="projectSlug")


class GetGuestProfileDetailsResponseDocumentsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    name: str
    id: str
    size: float
    status: str
    file_type: str = Field(alias="fileType")
    date_extracted: Any | None = Field(alias="dateExtracted")


class GetGuestProfileDetailsResponseCreatedBy(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    user_id: str = Field(alias="userId")
    email: str


class GetGuestProfileDetailsResponseSocialMediaLinksItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    social_media_type: Literal[
        "beehiiv",
        "behance",
        "bluesky",
        "discord",
        "facebook",
        "github",
        "instagram",
        "linkedin",
        "linktree",
        "mastodon",
        "medium",
        "patreon",
        "pinterest",
        "reddit",
        "snapchat",
        "soundcloud",
        "substack",
        "threads",
        "tiktok",
        "tumblr",
        "twitch",
        "twitter",
        "vimeo",
        "whatsapp",
        "youtube",
    ] = Field(alias="socialMediaType")
    url: str
    last_scraped_at: Any | None = Field(alias="lastScrapedAt")
    last_scrape_failed_at: Any | None = Field(alias="lastScrapeFailedAt")
    is_scraping: bool = Field(alias="isScraping")


class GetGuestProfileDetailsResponseGuestBio(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    additional_context: str | None = Field(alias="additionalContext")
    areas_of_expertise: list[str] = Field(alias="areasOfExpertise")
    goals: list[str]
    long_bio: str = Field(alias="longBio")
    short_bio: str = Field(alias="shortBio")
    things_to_avoid: list[str] = Field(alias="thingsToAvoid")
    topics_to_discuss: list[str] = Field(alias="topicsToDiscuss")


class GetGuestProfileDetailsResponsePublicViewSettings(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    display_linked_in: bool = Field(alias="displayLinkedIn")
    display_socials: bool = Field(alias="displaySocials")
    display_previous_podcast_appearances: bool = Field(alias="displayPreviousPodcastAppearances")
    marketing_letter_markdown_text: str | None = Field(alias="marketingLetterMarkdownText")
    public_slug: str | None = Field(alias="publicSlug")


class GetGuestProfileDetailsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_id: str = Field(alias="projectId")
    project_slug: str = Field(alias="projectSlug")
    guest_profile_id: str = Field(alias="guestProfileId")
    guest_profile_slug: str = Field(alias="guestProfileSlug")
    public_slug: str | None = Field(alias="publicSlug")
    name: str
    status: Literal["ACTIVE", "DRAFT", "PENDING", "ARCHIVED", "ERROR"]
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    documents: list[GetGuestProfileDetailsResponseDocumentsItem]
    listed_podcasts_count: float = Field(alias="listedPodcastsCount")
    booking_url: str | None = Field(alias="bookingUrl")
    company_name: str | None = Field(alias="companyName")
    email: str | None
    first_name: str | None = Field(alias="firstName")
    last_name: str | None = Field(alias="lastName")
    one_pager_url: str | None = Field(alias="onePagerUrl")
    phone: str | None
    website_url: str | None = Field(alias="websiteUrl")
    image_url: str | None = Field(alias="imageUrl")
    created_by: GetGuestProfileDetailsResponseCreatedBy = Field(alias="createdBy")
    social_media_links: list[GetGuestProfileDetailsResponseSocialMediaLinksItem] = Field(alias="socialMediaLinks")
    guest_bio: GetGuestProfileDetailsResponseGuestBio | None = Field(alias="guestBio")
    public_view_settings: GetGuestProfileDetailsResponsePublicViewSettings | None = Field(alias="publicViewSettings")


class UpdateGuestProfileBioResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    success: bool


class UpdateGuestProfileSocialMediaLinksBodyItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    social_media_type: Literal[
        "beehiiv",
        "behance",
        "bluesky",
        "discord",
        "facebook",
        "github",
        "instagram",
        "linkedin",
        "linktree",
        "mastodon",
        "medium",
        "patreon",
        "pinterest",
        "reddit",
        "snapchat",
        "soundcloud",
        "substack",
        "threads",
        "tiktok",
        "tumblr",
        "twitch",
        "twitter",
        "vimeo",
        "whatsapp",
        "youtube",
    ] = Field(alias="socialMediaType")
    url: str


class UpdateGuestProfileSocialMediaLinksResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    success: bool
    linked_in_scrape_trigger_failures: list[str] | None = Field(default=None, alias="linkedInScrapeTriggerFailures")


class RegenerateBioResponseResultAnswer(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    short_bio: str = Field(alias="shortBio")
    long_bio: str = Field(alias="longBio")
    goals: Any
    things_to_avoid: Any = Field(alias="thingsToAvoid")
    areas_of_expertise: Any = Field(alias="areasOfExpertise")
    topics_to_discuss: Any = Field(alias="topicsToDiscuss")


class RegenerateBioResponseResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    answer: RegenerateBioResponseResultAnswer


class RegenerateBioResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    result: RegenerateBioResponseResult


class UploadDocumentsResponseUploadedDocumentsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    file_name: str = Field(alias="fileName")
    file_size: float = Field(alias="fileSize")


class UploadDocumentsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    uploaded_documents: list[UploadDocumentsResponseUploadedDocumentsItem] = Field(alias="uploadedDocuments")


class GetLatestPodcastsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcasts: list[GetLatestEpisodesResponseLatestPodcastsItemPodcast]


class GetMultiplePodcastsResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_ids: list[str] = Field(alias="podcastIds")
    details: Literal["basic", "full"]


class GetMultiplePodcastsResponsePodcastsItemVariant2Blocked(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    blocked_date: Any = Field(alias="blockedDate")
    blocked_reason: str | None = Field(default=None, alias="blockedReason")


class GetMultiplePodcastsResponsePodcastsItemVariant2PodcastAffiliation(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    affiliate_organization_name: str | None = Field(default=None, alias="affiliateOrganizationName")
    affiliation_type: (
        Literal[
            "academic",
            "branded",
            "celebrity",
            "government",
            "independent",
            "legacy media",
            "podcast company",
            "new media",
            "not for profit",
            "religious",
            "other",
            "unknown",
        ]
        | None
    ) = Field(default=None, alias="affiliationType")


class GetMultiplePodcastsResponsePodcastsItemVariant2PodcastDirectoryLinks(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    amazonmusic: str | None = None
    anchor: str | None = None
    antennapod: str | None = None
    anytimeplayer: str | None = None
    apollo: str | None = None
    apple: str | None = None
    audible: str | None = None
    breez: str | None = None
    castamatic: str | None = None
    castbox: str | None = None
    castro: str | None = None
    curiocaster: str | None = None
    fountain: str | None = None
    goodpods: str | None = None
    google: str | None = None
    gpodder: str | None = None
    iheartradio: str | None = None
    listennotes: str | None = None
    lnbeats: str | None = None
    moonfm: str | None = None
    overcast: str | None = None
    playerfm: str | None = None
    pocketcasts: str | None = None
    podbean: str | None = None
    podcastaddict: str | None = None
    podcastguru: str | None = None
    podcastrepublic: str | None = None
    podchaser: str | None = None
    podfriend: str | None = None
    podknife: str | None = None
    podlp: str | None = None
    podnews: str | None = None
    podscan: str | None = None
    podscribe: str | None = None
    podstation: str | None = None
    podurama: str | None = None
    podverse: str | None = None
    radiopublic: str | None = None
    rephonic: str | None = None
    sonnet: str | None = None
    spotify: str | None = None
    stenofm: str | None = None
    truefans: str | None = None
    tunein: str | None = None
    youtubemusic: str | None = None


class GetMultiplePodcastsResponsePodcastsItemVariant2SocialMediaLinksItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    social_media_type: Literal[
        "beehiiv",
        "behance",
        "bluesky",
        "discord",
        "facebook",
        "github",
        "instagram",
        "linkedin",
        "linktree",
        "mastodon",
        "medium",
        "patreon",
        "pinterest",
        "reddit",
        "snapchat",
        "soundcloud",
        "substack",
        "threads",
        "tiktok",
        "tumblr",
        "twitch",
        "twitter",
        "vimeo",
        "whatsapp",
        "youtube",
    ] = Field(alias="socialMediaType")
    url: str
    sources: list[
        Literal[
            "apple-podcasts",
            "bright-data-dataset",
            "google-search",
            "linktree",
            "podcast-website",
            "podchaser",
            "rephonic",
            "rss",
        ]
    ]


class GetMultiplePodcastsResponsePodcastsItemVariant2Stats(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    download_count: float = Field(alias="downloadCount")
    episode_count: float = Field(alias="episodeCount")
    latest_published_at: Any | None = Field(alias="latestPublishedAt")
    first_episode_published_at: Any | None = Field(alias="firstEpisodePublishedAt")
    transcripts_count: float = Field(alias="transcriptsCount")
    update_frequency: Literal["daily", "weekly", "bi-weekly", "monthly", "stale", "very-stale"] = Field(
        alias="updateFrequency"
    )


class GetMultiplePodcastsResponsePodcastsItemVariant2TranscriptionModeVariant1(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    mode: Literal["none"]
    transcribe_since: Any | None = Field(default=None, alias="transcribeSince")


class GetMultiplePodcastsResponsePodcastsItemVariant2TranscriptionModeVariant2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    mode: Literal["all"]
    transcribe_since: Any | None = Field(default=None, alias="transcribeSince")


class GetMultiplePodcastsResponsePodcastsItemVariant2TranscriptionModeVariant3(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    mode: Literal["episodes-since"]
    transcribe_since: Any = Field(alias="transcribeSince")


class GetMultiplePodcastsResponsePodcastsItemVariant2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    author: str | None
    authority_score: GetChartResponseChartPositionsItemPodenginePodcastAuthorityScore | None = Field(
        alias="authorityScore"
    )
    genres: list[str]
    id: str
    image_url: str | None = Field(alias="imageUrl")
    language: str
    last_episode_published_at: Any = Field(alias="lastEpisodePublishedAt")
    slug: str
    title: str
    title_latest: str = Field(alias="titleLatest")
    apple_id: float = Field(alias="appleId")
    blocked: GetMultiplePodcastsResponsePodcastsItemVariant2Blocked | None = None
    description: str | None
    emails: list[str]
    explicit_rss: bool | None = Field(alias="explicitRss")
    host_names: list[str] | None = Field(alias="hostNames")
    ignore: bool
    ignore_reason: str | None = Field(default=None, alias="ignoreReason")
    never_transcribe: bool | None = Field(default=None, alias="neverTranscribe")
    never_transcribe_reason: str | None = Field(default=None, alias="neverTranscribeReason")
    is_claimed: bool = Field(alias="isClaimed")
    podcast_affiliation: GetMultiplePodcastsResponsePodcastsItemVariant2PodcastAffiliation | None = Field(
        alias="podcastAffiliation"
    )
    podcast_directory_links: GetMultiplePodcastsResponsePodcastsItemVariant2PodcastDirectoryLinks = Field(
        alias="podcastDirectoryLinks"
    )
    podcast_has_guests: bool | None = Field(alias="podcastHasGuests")
    podcast_has_sponsors: bool | None = Field(alias="podcastHasSponsors")
    podcast_locations: list[str] | None = Field(alias="podcastLocations")
    primary_contact_email: str | None = Field(alias="primaryContactEmail")
    rss_feed_url: str = Field(alias="rssFeedUrl")
    social_media_links: list[GetMultiplePodcastsResponsePodcastsItemVariant2SocialMediaLinksItem] = Field(
        alias="socialMediaLinks"
    )
    spotify_id: str | None = Field(alias="spotifyId")
    stats: GetMultiplePodcastsResponsePodcastsItemVariant2Stats
    title_latest_cleaned: str | None = Field(alias="titleLatestCleaned")
    transcription_mode: (
        GetMultiplePodcastsResponsePodcastsItemVariant2TranscriptionModeVariant1
        | GetMultiplePodcastsResponsePodcastsItemVariant2TranscriptionModeVariant2
        | GetMultiplePodcastsResponsePodcastsItemVariant2TranscriptionModeVariant3
    ) = Field(alias="transcriptionMode")
    website_url: str | None = Field(alias="websiteUrl")
    audience_estimate: GetLatestEpisodesResponseLatestPodcastsItemEpisodesItemAudienceEstimate | None = Field(
        default=None, alias="audienceEstimate"
    )
    audio_retention_policy: Literal["RETAIN_INDEFINITELY", "RETAIN_DAYS", "RETAIN_UNTIL_TRANSCRIBED"] | None = Field(
        default=None, alias="audioRetentionPolicy"
    )
    audio_retention_days: float | None = Field(default=None, alias="audioRetentionDays")


class GetMultiplePodcastsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetMultiplePodcastsResponseOptions
    total_requested: float = Field(alias="totalRequested")
    total_found: float = Field(alias="totalFound")
    podcasts: list[GetLatestEpisodesResponseLatestPodcastsItemPodcast | GetMultiplePodcastsResponsePodcastsItemVariant2]


class GetPodcastIdLookupResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetChartResponseChartPositionsItemPodenginePodcast | None


class GetAppleIdComprehensiveLookupResponsePodcast(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    slug: str
    title: str
    image_url: str | None = Field(alias="imageUrl")
    is_primary_apple_id: bool = Field(alias="isPrimaryAppleId")
    primary_apple_id: float = Field(alias="primaryAppleId")
    created_at: Any = Field(alias="createdAt")
    pod_engine_url: str = Field(alias="podEngineUrl")


class GetAppleIdComprehensiveLookupResponseImportRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: float
    apple_title: str = Field(alias="appleTitle")
    rss_url: str = Field(alias="rssUrl")
    creation_source: str = Field(alias="creationSource")
    created_at: Any = Field(alias="createdAt")
    imported_at: Any | None = Field(alias="importedAt")
    podcast_id: str | None = Field(alias="podcastId")
    import_error_at: Any | None = Field(alias="importErrorAt")
    import_error: str | None = Field(alias="importError")
    import_error_type: str | None = Field(alias="importErrorType")


class GetAppleIdComprehensiveLookupResponseScraperDataEntriesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: float
    country: str
    podcast_title: str = Field(alias="podcastTitle")
    created_at: Any = Field(alias="createdAt")
    last_scraped_at: Any | None = Field(alias="lastScrapedAt")
    last_success_at: Any | None = Field(alias="lastSuccessAt")
    last_error_at: Any | None = Field(alias="lastErrorAt")
    rss_url: str | None = Field(alias="rssUrl")
    ratings_count: float | None = Field(alias="ratingsCount")
    average_rating: float | None = Field(alias="averageRating")
    episodes_count: float | None = Field(alias="episodesCount")
    last_episode_date: Any | None = Field(alias="lastEpisodeDate")
    is_likely_non_english_title: bool = Field(alias="isLikelyNonEnglishTitle")
    skipped_podcast_import_reason: str | None = Field(alias="skippedPodcastImportReason")
    skipped_podcast_import_at: Any | None = Field(alias="skippedPodcastImportAt")


class GetAppleIdComprehensiveLookupResponseScraperDataRecentAttemptsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: float
    created_at: Any = Field(alias="createdAt")
    type: str
    url: str
    apple_id: float | None = Field(alias="appleId")
    spotify_id: str | None = Field(alias="spotifyId")
    podcast_id: str | None = Field(alias="podcastId")
    error_type: str | None = Field(alias="errorType")
    error_details: str | None = Field(alias="errorDetails")
    time_taken_ms: float = Field(alias="timeTakenMs")


class GetAppleIdComprehensiveLookupResponseScraperData(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    entries: list[GetAppleIdComprehensiveLookupResponseScraperDataEntriesItem]
    countries: list[str]
    most_recent_scrape: Any | None = Field(alias="mostRecentScrape")
    recent_attempts: list[GetAppleIdComprehensiveLookupResponseScraperDataRecentAttemptsItem] = Field(
        alias="recentAttempts"
    )


class GetAppleIdComprehensiveLookupResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    apple_id: float = Field(alias="appleId")
    status: Literal[
        "found",
        "linked",
        "apple_details_not_found",
        "apple_not_scraped",
        "create_podcast_failed",
        "duplicate_apple_id",
        "duplicate_podcast_guid",
        "duplicate_rss_url",
        "malformed_apple_url",
        "no_episodes_count",
        "no_podcast_image",
        "non_us_apple_url",
        "not_active",
        "request_not_found",
        "rss_download_failed",
        "rss_parsing_failed",
        "rss_url_not_found",
        "import_error_unknown",
        "pending_import",
        "scraped_not_imported_non_english",
        "scraped_not_imported_no_rss_url",
        "scraped_not_imported_not_fully_scraped",
        "scraped_not_imported_too_few_episodes",
        "scraped_not_imported_inactive",
        "scraped_not_imported_low_engagement",
        "scraped_not_imported_unknown",
        "not_found",
    ]
    podcast: GetAppleIdComprehensiveLookupResponsePodcast | None
    import_request: GetAppleIdComprehensiveLookupResponseImportRequest | None = Field(alias="importRequest")
    scraper_data: GetAppleIdComprehensiveLookupResponseScraperData | None = Field(alias="scraperData")


class GetPodcastAllDetailsResponsePodcastContactsEmailsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    email: str
    verified_at: Any | None = Field(alias="verifiedAt")
    syntax_valid: bool | None = Field(alias="syntaxValid")
    mx_valid: bool | None = Field(alias="mxValid")
    deep_verified_at: Any | None = Field(alias="deepVerifiedAt")
    deliverability_status: (
        Literal["valid", "invalid", "catch-all", "unknown", "spamtrap", "abuse", "do_not_mail"] | None
    ) = Field(alias="deliverabilityStatus")
    deliverability_reason: str | None = Field(alias="deliverabilityReason")
    is_free_email_provider: bool | None = Field(alias="isFreeEmailProvider")
    suggested_correction: str | None = Field(alias="suggestedCorrection")


class GetPodcastAllDetailsResponsePodcastContactsWebsitesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    url: str
    verified: bool
    contact_urls: list[str] = Field(alias="contactUrls")


class GetPodcastAllDetailsResponsePodcastContacts(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    emails: list[GetPodcastAllDetailsResponsePodcastContactsEmailsItem]
    phone_numbers: list[str] = Field(alias="phoneNumbers")
    websites: list[GetPodcastAllDetailsResponsePodcastContactsWebsitesItem]


class GetPodcastAllDetailsResponsePodcastGuestsGuestsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    name: str
    type: Literal["host", "guest", "unknown", "mentioned"]
    image_url: str | None = Field(alias="imageUrl")
    appearances_count: float = Field(alias="appearancesCount")
    most_recent_appearance_date: Any = Field(alias="mostRecentAppearanceDate")
    oldest_appearance_date: Any = Field(alias="oldestAppearanceDate")


class GetPodcastAllDetailsResponsePodcastGuests(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    episodes_count: float = Field(alias="episodesCount")
    episodes_with_guests_count: float = Field(alias="episodesWithGuestsCount")
    most_recent_episode_date: Any = Field(alias="mostRecentEpisodeDate")
    oldest_episode_date: Any = Field(alias="oldestEpisodeDate")
    guests: list[GetPodcastAllDetailsResponsePodcastGuestsGuestsItem]


class GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReview(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    apple_id: float = Field(alias="appleId")
    scraped_at: Any = Field(alias="scrapedAt")
    country: str
    reviews_count: float = Field(alias="reviewsCount")
    rating: float | None
    one_star_count: float = Field(alias="oneStarCount")
    two_star_count: float = Field(alias="twoStarCount")
    three_star_count: float = Field(alias="threeStarCount")
    four_star_count: float = Field(alias="fourStarCount")
    five_star_count: float = Field(alias="fiveStarCount")


class GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewsByCountryItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    apple_id: float = Field(alias="appleId")
    scraped_at: Any = Field(alias="scrapedAt")
    country: str
    reviews_count: float = Field(alias="reviewsCount")
    rating: float | None
    one_star_count: float = Field(alias="oneStarCount")
    two_star_count: float = Field(alias="twoStarCount")
    three_star_count: float = Field(alias="threeStarCount")
    four_star_count: float = Field(alias="fourStarCount")
    five_star_count: float = Field(alias="fiveStarCount")


class GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewTextReviewsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    country: str
    rating: float
    title: str
    body: str
    author: str
    reviewed_at: Any = Field(alias="reviewedAt")


class GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewText(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    country: str | None
    total: float
    limit: float
    offset: float
    reviews: list[GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewTextReviewsItem]


class GetPodcastAllDetailsResponsePodcastReviewsSpotifyReview(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    spotify_id: str = Field(alias="spotifyId")
    scraped_at: Any = Field(alias="scrapedAt")
    reviews_count: float = Field(alias="reviewsCount")
    rating: float | None


class GetPodcastAllDetailsResponsePodcastReviewsCastbox(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    scraped_at: Any = Field(alias="scrapedAt")
    plays: float
    subscribers: float


class GetPodcastAllDetailsResponsePodcastReviews(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    apple_id: float = Field(alias="appleId")
    spotify_id: str | None = Field(alias="spotifyId")
    apple_podcasts_review: GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReview | None = Field(
        alias="applePodcastsReview"
    )
    apple_podcasts_reviews_by_country: list[
        GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewsByCountryItem
    ] = Field(alias="applePodcastsReviewsByCountry")
    apple_podcasts_review_text: GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewText | None = Field(
        alias="applePodcastsReviewText"
    )
    spotify_review: GetPodcastAllDetailsResponsePodcastReviewsSpotifyReview | None = Field(alias="spotifyReview")
    castbox: GetPodcastAllDetailsResponsePodcastReviewsCastbox | None


class GetPodcastAllDetailsResponsePodcastSocialMediaFacebookPageDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    facebook_page_id: str = Field(alias="facebookPageId")
    profile_photo_url: str | None = Field(alias="profilePhotoUrl")
    name: str
    followers: float
    likes: float
    following: float
    talking_about_count: float | None = Field(alias="talkingAboutCount")
    facebook_page_url: str = Field(alias="facebookPageUrl")
    scraped_at: Any = Field(alias="scrapedAt")


class GetPodcastAllDetailsResponsePodcastSocialMediaInstagramDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_id: float = Field(alias="profileId")
    followers: float
    following: float
    posts: float
    instagram_profile_name: str = Field(alias="instagramProfileName")
    profile_photo_url: str | None = Field(alias="profilePhotoUrl")
    scraped_at: Any = Field(alias="scrapedAt")


class GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInCompanyDataItemMostRecentUpdate(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    post_id: str = Field(alias="postId")
    likes_count: float = Field(alias="likesCount")
    comments_count: float = Field(alias="commentsCount")
    title: str
    text: str
    post_url: str = Field(alias="postUrl")
    date: Any


class GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInCompanyDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    scraped_at: Any = Field(alias="scrapedAt")
    linked_in_company_id: str = Field(alias="linkedInCompanyId")
    linked_in_url: str = Field(alias="linkedInUrl")
    name: str
    country_code: str | None = Field(alias="countryCode")
    followers: float
    employees_in_linkedin: float = Field(alias="employeesInLinkedin")
    about: str | None
    description: str | None
    company_size: str | None = Field(alias="companySize")
    industries: str | None
    logo_image_url: str | None = Field(alias="logoImageUrl")
    most_recent_update: GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInCompanyDataItemMostRecentUpdate | None = (
        Field(alias="mostRecentUpdate")
    )


class GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInPersonDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    scraped_at: Any = Field(alias="scrapedAt")
    name: str
    profile_photo_url: str | None = Field(alias="profilePhotoUrl")
    linked_in_profile_id: str = Field(alias="linkedInProfileId")
    linked_in_numeric_id: float = Field(alias="linkedInNumericId")
    avatar_url: str | None = Field(alias="avatarUrl")
    city: str | None
    country_code: str | None = Field(alias="countryCode")
    description: str | None
    about: str | None
    location: str | None
    follower_count: float = Field(alias="followerCount")
    connections_count: float = Field(alias="connectionsCount")
    recommendations_count: float = Field(alias="recommendationsCount")


class GetPodcastAllDetailsResponsePodcastSocialMediaTiktokDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    account_id: str = Field(alias="accountId")
    awg_engagement_rate: float | None = Field(alias="awgEngagementRate")
    biography: str | None
    comment_engagement_rate: float | None = Field(alias="commentEngagementRate")
    date_joined: Any = Field(alias="dateJoined")
    followers: float
    following: float
    is_private: bool = Field(alias="isPrivate")
    is_verified: bool = Field(alias="isVerified")
    like_engagement_rate: float | None = Field(alias="likeEngagementRate")
    likes: float
    nickname: str
    handle: str
    profile_pic_url: str | None = Field(alias="profilePicUrl")
    videos_count: float = Field(alias="videosCount")
    scraped_at: Any = Field(alias="scrapedAt")


class GetPodcastAllDetailsResponsePodcastSocialMediaTwitterDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_id: str = Field(alias="profileId")
    profile_name: str = Field(alias="profileName")
    profile_url: str = Field(alias="profileUrl")
    profile_image_url: str | None = Field(alias="profileImageUrl")
    biography: str | None
    following_count: int = Field(alias="followingCount")
    follower_count: int = Field(alias="followerCount")
    posts_count: int = Field(alias="postsCount")
    date_joined: Any | None = Field(alias="dateJoined")
    scraped_at: Any = Field(alias="scrapedAt")


class GetPodcastAllDetailsResponsePodcastSocialMedia(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    social_media_links: list[GetMultiplePodcastsResponsePodcastsItemVariant2SocialMediaLinksItem] = Field(
        alias="socialMediaLinks"
    )
    facebook_page_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaFacebookPageDataItem] = Field(
        alias="facebookPageData"
    )
    instagram_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaInstagramDataItem] = Field(alias="instagramData")
    linked_in_company_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInCompanyDataItem] = Field(
        alias="linkedInCompanyData"
    )
    linked_in_person_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInPersonDataItem] = Field(
        alias="linkedInPersonData"
    )
    tiktok_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaTiktokDataItem] = Field(alias="tiktokData")
    twitter_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaTwitterDataItem] = Field(alias="twitterData")


class GetPodcastAllDetailsResponsePodcastSponsorsSponsorsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    name: str
    image_url: str | None = Field(alias="imageUrl")
    appearances_count: float = Field(alias="appearancesCount")
    most_recent_appearance_date: Any = Field(alias="mostRecentAppearanceDate")
    oldest_appearance_date: Any = Field(alias="oldestAppearanceDate")


class GetPodcastAllDetailsResponsePodcastSponsors(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    episodes_count: float = Field(alias="episodesCount")
    episodes_with_sponsors_count: float = Field(alias="episodesWithSponsorsCount")
    most_recent_episode_date: Any = Field(alias="mostRecentEpisodeDate")
    oldest_episode_date: Any = Field(alias="oldestEpisodeDate")
    sponsors: list[GetPodcastAllDetailsResponsePodcastSponsorsSponsorsItem]


class GetPodcastAllDetailsResponsePodcastRelatedPodcasts(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    similar_podcasts: list[GetLatestEpisodesResponseLatestPodcastsItemPodcast] = Field(alias="similarPodcasts")


class GetPodcastAllDetailsResponsePodcastChartPositionsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    chart_date: str = Field(alias="chartDate")
    chart_type: Literal["apple", "spotify"] = Field(alias="chartType")
    country: str
    category: str
    position: float


class GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItemThumbnails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    default: str | None
    medium: str | None
    high: str | None


class GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItemVideosItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    image_url: str = Field(alias="imageUrl")
    is_short: bool = Field(alias="isShort")
    posted_at: Any = Field(alias="postedAt")
    posted_at_relative: str = Field(alias="postedAtRelative")
    scraped_at: Any = Field(alias="scrapedAt")
    title: str
    video_url: str = Field(alias="videoUrl")
    views: float


class GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str
    description: str | None
    subscriber_count: float = Field(alias="subscriberCount")
    view_count: float = Field(alias="viewCount")
    video_count: float = Field(alias="videoCount")
    published_at: Any | None = Field(alias="publishedAt")
    thumbnails: GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItemThumbnails
    country: str | None
    custom_url: str | None = Field(alias="customUrl")
    links: list[str] | None
    is_podcast_channel: bool | None = Field(alias="isPodcastChannel")
    discover_input_keyword: str | None = Field(alias="discoverInputKeyword")
    banner_image_url: str | None = Field(alias="bannerImageUrl")
    videos: list[GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItemVideosItem] | None
    profile_image_url: str | None = Field(alias="profileImageUrl")
    data_last_updated: Any = Field(alias="dataLastUpdated")
    last_video_upload_date: Any | None = Field(alias="lastVideoUploadDate")
    last_video_upload_date_source: str | None = Field(alias="lastVideoUploadDateSource")
    last_video_upload_date_checked_at: Any | None = Field(alias="lastVideoUploadDateCheckedAt")


class GetPodcastAllDetailsResponsePodcastYoutubeData(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    youtube_data: list[GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItem] = Field(alias="youtubeData")


class GetPodcastAllDetailsResponsePodcast(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetMultiplePodcastsResponsePodcastsItemVariant2
    recent_episodes: list[GetLatestEpisodesResponseLatestPodcastsItemEpisodesItem] | None = Field(
        alias="recentEpisodes"
    )
    contacts: GetPodcastAllDetailsResponsePodcastContacts | None
    guests: GetPodcastAllDetailsResponsePodcastGuests | None
    reviews: GetPodcastAllDetailsResponsePodcastReviews | None
    social_media: GetPodcastAllDetailsResponsePodcastSocialMedia | None = Field(alias="socialMedia")
    sponsors: GetPodcastAllDetailsResponsePodcastSponsors | None
    related_podcasts: GetPodcastAllDetailsResponsePodcastRelatedPodcasts | None = Field(alias="relatedPodcasts")
    chart_positions: list[GetPodcastAllDetailsResponsePodcastChartPositionsItem] | None = Field(alias="chartPositions")
    youtube_data: GetPodcastAllDetailsResponsePodcastYoutubeData | None = Field(alias="youtubeData")


class GetPodcastAllDetailsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetPodcastAllDetailsResponsePodcast


class GetPodcastResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetMultiplePodcastsResponsePodcastsItemVariant2


class GetPodcastEpisodesResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    has_transcript: bool | None = Field(default=None, alias="hasTranscript")
    skip: float | None = None
    limit: float | None = None


class GetPodcastEpisodesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetPodcastEpisodesResponseOptions
    total_episodes: float = Field(alias="totalEpisodes")
    total_transcripts: float = Field(alias="totalTranscripts")
    podcast_with_episodes: GetLatestEpisodesResponseLatestPodcastsItem = Field(alias="podcastWithEpisodes")


class GetPodcastRelatedPodcastsResponseRelatedPodcasts(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    similar_podcasts: list[GetLatestEpisodesResponseLatestPodcastsItemPodcast] = Field(alias="similarPodcasts")


class GetPodcastRelatedPodcastsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    related_podcasts: GetPodcastRelatedPodcastsResponseRelatedPodcasts = Field(alias="relatedPodcasts")


class GetPodcastReviewsResponsePodcastReviews(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    apple_id: float = Field(alias="appleId")
    spotify_id: str | None = Field(alias="spotifyId")
    apple_podcasts_review: GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReview | None = Field(
        alias="applePodcastsReview"
    )
    apple_podcasts_reviews_by_country: list[
        GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewsByCountryItem
    ] = Field(alias="applePodcastsReviewsByCountry")
    apple_podcasts_review_text: GetPodcastAllDetailsResponsePodcastReviewsApplePodcastsReviewText | None = Field(
        alias="applePodcastsReviewText"
    )
    spotify_review: GetPodcastAllDetailsResponsePodcastReviewsSpotifyReview | None = Field(alias="spotifyReview")
    castbox: GetPodcastAllDetailsResponsePodcastReviewsCastbox | None


class GetPodcastReviewsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    podcast_reviews: GetPodcastReviewsResponsePodcastReviews = Field(alias="podcastReviews")


class GetPodcastContactsResponsePodcastContacts(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    emails: list[GetPodcastAllDetailsResponsePodcastContactsEmailsItem]
    phone_numbers: list[str] = Field(alias="phoneNumbers")
    websites: list[GetPodcastAllDetailsResponsePodcastContactsWebsitesItem]


class GetPodcastContactsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    podcast_contacts: GetPodcastContactsResponsePodcastContacts = Field(alias="podcastContacts")


class GetPodcastChartsResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    chart_type: Literal["apple", "spotify"] | None = Field(default=None, alias="chartType")
    category: str | None = None
    country: str | None = None
    positions_limit: float | None = Field(default=None, alias="positionsLimit")
    limit: float | None = None


class GetPodcastChartsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    options: GetPodcastChartsResponseOptions
    total_charts: float = Field(alias="totalCharts")
    positions: list[GetPodcastAllDetailsResponsePodcastChartPositionsItem]


class GetPodcastSocialMediaDetailsResponseSocialMediaData(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    social_media_links: list[GetMultiplePodcastsResponsePodcastsItemVariant2SocialMediaLinksItem] = Field(
        alias="socialMediaLinks"
    )
    facebook_page_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaFacebookPageDataItem] = Field(
        alias="facebookPageData"
    )
    instagram_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaInstagramDataItem] = Field(alias="instagramData")
    linked_in_company_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInCompanyDataItem] = Field(
        alias="linkedInCompanyData"
    )
    linked_in_person_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaLinkedInPersonDataItem] = Field(
        alias="linkedInPersonData"
    )
    tiktok_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaTiktokDataItem] = Field(alias="tiktokData")
    twitter_data: list[GetPodcastAllDetailsResponsePodcastSocialMediaTwitterDataItem] = Field(alias="twitterData")


class GetPodcastSocialMediaDetailsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    social_media_data: GetPodcastSocialMediaDetailsResponseSocialMediaData = Field(alias="socialMediaData")


class GetPodcastYoutubeDetailsResponseYoutubeData(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    youtube_data: list[GetPodcastAllDetailsResponsePodcastYoutubeDataYoutubeDataItem] = Field(alias="youtubeData")


class GetPodcastYoutubeDetailsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    youtube_data: GetPodcastYoutubeDetailsResponseYoutubeData = Field(alias="youtubeData")


class RequestPodcastTranscriptionResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    message: str
    episode_ids: list[str] = Field(alias="episodeIds")


class RefreshPodcastResponseVariant1(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    success: Literal[True]
    podcast: GetMultiplePodcastsResponsePodcastsItemVariant2


class RefreshPodcastResponseVariant2ErrorDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    rss_url: str | None = Field(default=None, alias="rssUrl")
    attempt_id: float | None = Field(default=None, alias="attemptId")


class RefreshPodcastResponseVariant2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    success: Literal[False]
    error_code: Literal["rss_not_found", "rss_parse_error", "rss_fetch_failed", "update_failed", "unknown_error"] = (
        Field(alias="errorCode")
    )
    error_message: str = Field(alias="errorMessage")
    error_details: RefreshPodcastResponseVariant2ErrorDetails | None = Field(default=None, alias="errorDetails")


class GetUpdatesResponseEventsItemVariant1Data(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    request_id: str = Field(alias="requestId")
    request_type: Literal["autoOutreach", "deepAnalysis", "diarization", "guestPrep", "transcription"] = Field(
        alias="requestType"
    )
    podcast_id: str = Field(alias="podcastId")
    episode_id: str | None = Field(alias="episodeId")
    guest_profile_id: str | None = Field(alias="guestProfileId")
    completed_at: datetime = Field(alias="completedAt")
    error: str | None


class GetUpdatesResponseEventsItemVariant1(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    occurred_at: datetime = Field(alias="occurredAt")
    event_type: Literal["request_completed"] = Field(alias="eventType")
    data: GetUpdatesResponseEventsItemVariant1Data


class GetUpdatesResponseEventsItemVariant2Data(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    guest_appearance_id: str = Field(alias="guestAppearanceId")
    guest_profile_id: str = Field(alias="guestProfileId")
    episode_id: str = Field(alias="episodeId")
    ai_verified: bool | None = Field(alias="aiVerified")
    human_verified: bool | None = Field(alias="humanVerified")
    created_at: datetime = Field(alias="createdAt")


class GetUpdatesResponseEventsItemVariant2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    occurred_at: datetime = Field(alias="occurredAt")
    event_type: Literal["guest_appearance"] = Field(alias="eventType")
    data: GetUpdatesResponseEventsItemVariant2Data


class GetUpdatesResponseEventsItemVariant3Data(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    listed_podcast_id: str = Field(alias="listedPodcastId")
    project_id: str = Field(alias="projectId")
    podcast_id: str = Field(alias="podcastId")
    status: Literal["prospect", "qualified", "pitched", "lost", "booked", "ignored"]
    created_at: datetime = Field(alias="createdAt")


class GetUpdatesResponseEventsItemVariant3(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    occurred_at: datetime = Field(alias="occurredAt")
    event_type: Literal["listed_podcast_added"] = Field(alias="eventType")
    data: GetUpdatesResponseEventsItemVariant3Data


class GetUpdatesResponseEventsItemVariant4Data(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    alert_match_id: str = Field(alias="alertMatchId")
    alert_config_id: str = Field(alias="alertConfigId")
    alert_config_name: str = Field(alias="alertConfigName")
    alert_type: Literal["TRANSCRIPT", "EPISODE"] = Field(alias="alertType")
    episode_id: str = Field(alias="episodeId")
    podcast_id: str = Field(alias="podcastId")
    created_at: datetime = Field(alias="createdAt")


class GetUpdatesResponseEventsItemVariant4(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    occurred_at: datetime = Field(alias="occurredAt")
    event_type: Literal["alert_match"] = Field(alias="eventType")
    data: GetUpdatesResponseEventsItemVariant4Data


class GetUpdatesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    events: list[
        GetUpdatesResponseEventsItemVariant1
        | GetUpdatesResponseEventsItemVariant2
        | GetUpdatesResponseEventsItemVariant3
        | GetUpdatesResponseEventsItemVariant4
    ]
    cursor: str | None
    has_more: bool = Field(alias="hasMore")


class GetProjectsResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    states: Any | None = None
    sort_by: Literal["recent-activity", "name", "created"] | None = Field(default=None, alias="sortBy")


class GetProjectsResponseProjectsItemCreatedBy(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    display_name: str | None = Field(alias="displayName")
    avatar_seed: str | None = Field(alias="avatarSeed")


class GetProjectsResponseProjectsItemLinkedGuestProfile(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    slug: str
    status: Literal["ACTIVE", "DRAFT", "PENDING", "ARCHIVED", "ERROR"]
    image_url: str | None = Field(alias="imageUrl")
    linkedin_url: str | None = Field(alias="linkedinUrl")
    appearances_count: float = Field(alias="appearancesCount")


class GetProjectsResponseProjectsItemStateCounts(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    prospect: float
    qualified: float
    pitched: float
    booked: float
    lost: float
    ignored: float


class GetProjectsResponseProjectsItemDocumentsCount(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total: float
    processed: float


class GetProjectsResponseProjectsItemRecentActivitiesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    type: Literal["added-to-list", "update-labels", "update-priority", "update-state"]
    date: Any
    podcast_title: str | None = Field(alias="podcastTitle")
    podcast_slug: str | None = Field(alias="podcastSlug")
    podcast_image_url: str | None = Field(alias="podcastImageUrl")
    to_value: str | None = Field(alias="toValue")
    user: GetProjectsResponseProjectsItemCreatedBy | None


class GetProjectsResponseProjectsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_id: str = Field(alias="projectId")
    name: str
    slug: str
    team_id: str = Field(alias="teamId")
    created_at: Any = Field(alias="createdAt")
    last_updated: Any = Field(alias="lastUpdated")
    created_by: GetProjectsResponseProjectsItemCreatedBy | None = Field(alias="createdBy")
    project_types: list[
        Literal[
            "advertisers",
            "api",
            "content-creation",
            "guest-booking",
            "interesting-podcasts",
            "lead-generation",
            "monitoring",
            "other",
            "transcriptions",
        ]
    ] = Field(alias="projectTypes")
    status: Literal["DRAFT", "PENDING", "ACTIVE", "ARCHIVED", "ERROR"]
    listed_podcasts_count: float = Field(alias="listedPodcastsCount")
    linked_guest_profile: GetProjectsResponseProjectsItemLinkedGuestProfile | None = Field(alias="linkedGuestProfile")
    state_counts: GetProjectsResponseProjectsItemStateCounts = Field(alias="stateCounts")
    documents_count: GetProjectsResponseProjectsItemDocumentsCount = Field(alias="documentsCount")
    recent_activities: list[GetProjectsResponseProjectsItemRecentActivitiesItem] = Field(alias="recentActivities")


class GetProjectsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    options: GetProjectsResponseOptions
    projects: list[GetProjectsResponseProjectsItem]


class GetProjectDetailsResponseProjectGoHighLevelIntegration(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    location_id: str = Field(alias="locationId")
    has_api_key: bool = Field(alias="hasApiKey")
    enabled: bool
    only_push_relevant_podcasts: bool = Field(alias="onlyPushRelevantPodcasts")


class GetProjectDetailsResponseProject(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_id: str = Field(alias="projectId")
    name: str
    slug: str
    team_id: str = Field(alias="teamId")
    created_at: Any = Field(alias="createdAt")
    last_updated: Any = Field(alias="lastUpdated")
    created_by: GetProjectsResponseProjectsItemCreatedBy | None = Field(alias="createdBy")
    project_types: list[
        Literal[
            "advertisers",
            "api",
            "content-creation",
            "guest-booking",
            "interesting-podcasts",
            "lead-generation",
            "monitoring",
            "other",
            "transcriptions",
        ]
    ] = Field(alias="projectTypes")
    status: Literal["DRAFT", "PENDING", "ACTIVE", "ARCHIVED", "ERROR"]
    listed_podcasts_count: float = Field(alias="listedPodcastsCount")
    linked_guest_profile: GetProjectsResponseProjectsItemLinkedGuestProfile | None = Field(alias="linkedGuestProfile")
    state_counts: GetProjectsResponseProjectsItemStateCounts = Field(alias="stateCounts")
    documents_count: GetProjectsResponseProjectsItemDocumentsCount = Field(alias="documentsCount")
    recent_activities: list[GetProjectsResponseProjectsItemRecentActivitiesItem] = Field(alias="recentActivities")
    project_type_other_reason: str | None = Field(alias="projectTypeOtherReason")
    project_purpose: str | None = Field(alias="projectPurpose")
    project_keywords: list[str] = Field(alias="projectKeywords")
    public_title: str | None = Field(alias="publicTitle")
    public_description: str | None = Field(alias="publicDescription")
    public_slug: str | None = Field(alias="publicSlug")
    is_public_listicle: bool = Field(alias="isPublicListicle")
    public_podcast_limit: float = Field(alias="publicPodcastLimit")
    is_public_for_team: bool = Field(alias="isPublicForTeam")
    go_high_level_integration: GetProjectDetailsResponseProjectGoHighLevelIntegration | None = Field(
        alias="goHighLevelIntegration"
    )


class GetProjectDetailsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project: GetProjectDetailsResponseProject


class GetProjectStrategiesResponseStrategiesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    title: str
    short_description: str = Field(alias="shortDescription")
    strategy_blurb: str = Field(alias="strategyBlurb")
    audience_persona_target: str = Field(alias="audiencePersonaTarget")
    why_its_effective: str = Field(alias="whyItsEffective")
    strategy_training_documentation: str = Field(alias="strategyTrainingDocumentation")
    keyword_inspiration: list[str] = Field(alias="keywordInspiration")
    example_google_searches: list[str] = Field(alias="exampleGoogleSearches")
    id: str
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    strategy_approach: Literal["straightforward", "unconventional", "longshot"] | None = Field(alias="strategyApproach")
    strategy_focus: str | None = Field(alias="strategyFocus")
    priority: Literal["low", "medium", "high", "urgent"] | None
    auto_search_enabled: bool = Field(alias="autoSearchEnabled")


class GetProjectStrategiesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    strategies: list[GetProjectStrategiesResponseStrategiesItem]


class UpdateProjectResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project: GetProjectsResponseProjectsItem


class AddPodcastToProjectResponseListedPodcastPodcast(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    title_original: str = Field(alias="titleOriginal")
    title_latest: str = Field(alias="titleLatest")
    slug: str
    image_url: str | None = Field(alias="imageUrl")


class AddPodcastToProjectResponseListedPodcastAddedByUser(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    user_id: str = Field(alias="userId")
    email: str
    display_name: str | None = Field(alias="displayName")


class AddPodcastToProjectResponseListedPodcastActivityHistoryItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    action_type: Literal["added-to-list", "update-labels", "update-priority", "update-state"] = Field(
        alias="actionType"
    )
    activity_date: Any = Field(alias="activityDate")
    from_value: str | None = Field(alias="fromValue")
    to_value: str | None = Field(alias="toValue")
    user_id: str = Field(alias="userId")
    user_display_name: str = Field(alias="userDisplayName")


class AddPodcastToProjectResponseListedPodcastAnalysis(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    relevancy_score: float | None = Field(default=None, alias="relevancyScore")
    deep_relevancy_score: float | None = Field(default=None, alias="deepRelevancyScore")
    host_relevancy_score: float | None = Field(default=None, alias="hostRelevancyScore")


class AddPodcastToProjectResponseListedPodcast(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    listed_podcast_id: str = Field(alias="listedPodcastId")
    project_id: str = Field(alias="projectId")
    podcast: AddPodcastToProjectResponseListedPodcastPodcast
    status: Literal["prospect", "qualified", "pitched", "lost", "booked", "ignored"]
    priority: Literal["low", "medium", "high", "urgent"] | None
    labels: list[str]
    added_at: Any = Field(alias="addedAt")
    updated_at: Any = Field(alias="updatedAt")
    added_by_user: AddPodcastToProjectResponseListedPodcastAddedByUser = Field(alias="addedByUser")
    activity_history: list[AddPodcastToProjectResponseListedPodcastActivityHistoryItem] = Field(alias="activityHistory")
    analysis: AddPodcastToProjectResponseListedPodcastAnalysis


class AddPodcastToProjectResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    listed_podcast: AddPodcastToProjectResponseListedPodcast = Field(alias="listedPodcast")


class UpdateProjectListedPodcastResponseOptions(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    state: Literal["prospect", "qualified", "pitched", "lost", "booked", "ignored"] | None = None
    priority: Literal["low", "medium", "high", "urgent"] | None = None


class UpdateProjectListedPodcastResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_slug: str = Field(alias="projectSlug")
    listed_podcast_id: str = Field(alias="listedPodcastId")
    options: UpdateProjectListedPodcastResponseOptions
    updated_listed_podcast: AddPodcastToProjectResponseListedPodcast = Field(alias="updatedListedPodcast")


class RemoveListedPodcastFromProjectResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_slug: str = Field(alias="projectSlug")
    listed_podcast_id: str = Field(alias="listedPodcastId")


class SearchAutocompletePodcastsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcasts: list[GetLatestEpisodesResponseLatestPodcastsItemPodcast]
    words: list[str]


class SearchPodcastsResponseSeachResultsStatsTime(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total_time_taken_ms: float = Field(alias="totalTimeTakenMs")
    total_search_time_ms: float = Field(alias="totalSearchTimeMs")
    total_post_processing_time_ms: float = Field(alias="totalPostProcessingTimeMs")


class SearchPodcastsResponseSeachResultsStatsTotals(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    blacklisted_podcasts: float = Field(alias="blacklistedPodcasts")
    project_excluded_podcasts: float = Field(alias="projectExcludedPodcasts")
    total_results_available: float = Field(alias="totalResultsAvailable")
    results_processed: float = Field(alias="resultsProcessed")
    results_filtered: float = Field(alias="resultsFiltered")
    results_returned: float = Field(alias="resultsReturned")


class SearchPodcastsResponseSeachResultsStatsFiltersProjectPodcastRelevancyScoresValue(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    answer: AskAgentProjectPodcastRelevancyResponseResultAnswer


class SearchPodcastsResponseSeachResultsStatsFilters(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    relevancy_scores_totals: dict[str, float] = Field(alias="relevancyScoresTotals")
    project_podcast_relevancy_scores: (
        dict[str, SearchPodcastsResponseSeachResultsStatsFiltersProjectPodcastRelevancyScoresValue | None] | None
    ) = Field(default=None, alias="projectPodcastRelevancyScores")


class SearchPodcastsResponseSeachResultsStats(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    time: SearchPodcastsResponseSeachResultsStatsTime
    totals: SearchPodcastsResponseSeachResultsStatsTotals
    filters: SearchPodcastsResponseSeachResultsStatsFilters


class SearchPodcastsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    search_mode: Literal["podcasts"] = Field(alias="searchMode")
    search_id: str = Field(alias="searchId")
    search_options: AskAgentProjectPodcastRelevancySearchOptionsVariant1 = Field(alias="searchOptions")
    seach_results_stats: SearchPodcastsResponseSeachResultsStats = Field(alias="seachResultsStats")
    result: Any
    cursor: str | None


class SearchEpisodesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    search_mode: Literal["episodes"] = Field(alias="searchMode")
    search_id: str = Field(alias="searchId")
    search_options: AskAgentProjectPodcastRelevancySearchOptionsVariant2 = Field(alias="searchOptions")
    seach_results_stats: SearchPodcastsResponseSeachResultsStats = Field(alias="seachResultsStats")
    result: Any
    cursor: str | None


class GetRssStatsPodcast2ResponsePodcast2StatsPodcastLevelStatsFieldFrequencyItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    field: str
    frequency: float
    percentage: float


class GetRssStatsPodcast2ResponsePodcast2StatsPodcastLevelStats(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total_rss_feeds: float = Field(alias="totalRssFeeds")
    field_frequency: list[GetRssStatsPodcast2ResponsePodcast2StatsPodcastLevelStatsFieldFrequencyItem] = Field(
        alias="fieldFrequency"
    )


class GetRssStatsPodcast2ResponsePodcast2StatsTopPodcast2PodcastsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_id: str = Field(alias="podcastId")
    host: str
    podcast_slug: str = Field(alias="podcastSlug")
    podcast_image_url: str | None = Field(alias="podcastImageUrl")
    rss_feed_url: str = Field(alias="rssFeedUrl")
    num_podcast20_fields: float = Field(alias="numPodcast20Fields")
    implemented_fields: list[str] = Field(alias="implementedFields")


class GetRssStatsPodcast2ResponsePodcast2StatsTopHostsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    host: str
    total_podcasts: float = Field(alias="totalPodcasts")
    percentage: float


class GetRssStatsPodcast2ResponsePodcast2StatsTopHostsWithPodcast2TranscriptsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    host: str
    total_podcasts: float = Field(alias="totalPodcasts")
    num_podcasts_with_transcripts: float = Field(alias="numPodcastsWithTranscripts")
    percentage: float


class GetRssStatsPodcast2ResponsePodcast2StatsTopHostsWithPodcast2StatsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    host: str
    total_podcasts: float = Field(alias="totalPodcasts")
    average_num_podcast2_fields: float = Field(alias="averageNumPodcast2Fields")


class GetRssStatsPodcast2ResponsePodcast2Stats(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast_level_stats: GetRssStatsPodcast2ResponsePodcast2StatsPodcastLevelStats = Field(alias="podcastLevelStats")
    episode_level_stats: GetRssStatsPodcast2ResponsePodcast2StatsPodcastLevelStats = Field(alias="episodeLevelStats")
    top_podcast2_podcasts: list[GetRssStatsPodcast2ResponsePodcast2StatsTopPodcast2PodcastsItem] = Field(
        alias="topPodcast2Podcasts"
    )
    top_hosts: list[GetRssStatsPodcast2ResponsePodcast2StatsTopHostsItem] = Field(alias="topHosts")
    top_hosts_with_podcast2_transcripts: list[
        GetRssStatsPodcast2ResponsePodcast2StatsTopHostsWithPodcast2TranscriptsItem
    ] = Field(alias="topHostsWithPodcast2Transcripts")
    top_hosts_with_podcast2_stats: list[GetRssStatsPodcast2ResponsePodcast2StatsTopHostsWithPodcast2StatsItem] = Field(
        alias="topHostsWithPodcast2Stats"
    )


class GetRssStatsPodcast2Response(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    podcast2_stats: GetRssStatsPodcast2ResponsePodcast2Stats = Field(alias="podcast2Stats")


class GetTeamPodcastsResponseTeamPodcastsItemProjectsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    project_id: str = Field(alias="projectId")
    added_by_user_id: str = Field(alias="addedByUserId")
    listed_podcast_state: Literal["prospect", "qualified", "pitched", "lost", "booked", "ignored"] = Field(
        alias="listedPodcastState"
    )


class GetTeamPodcastsResponseTeamPodcastsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    added_by_user_id: str | None = Field(alias="addedByUserId")
    added_reason: Literal["add-to-team-podcasts-button", "listed-podcast", "migration", "script", "search-export"] = (
        Field(alias="addedReason")
    )
    blacklist: bool
    created_at: Any = Field(alias="createdAt")
    podcast: GetLatestEpisodesResponseLatestPodcastsItemPodcast
    podcast_id: str = Field(alias="podcastId")
    projects: list[GetTeamPodcastsResponseTeamPodcastsItemProjectsItem]
    sync: bool
    team_id: str = Field(alias="teamId")
    last_airtable_sync: Any | None = Field(default=None, alias="lastAirtableSync")
    last_airtable_error_sync_date: Any | None = Field(default=None, alias="lastAirtableErrorSyncDate")
    airtable_record_id: str | None = Field(default=None, alias="airtableRecordId")


class GetTeamPodcastsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total: float
    total_filtered: float = Field(alias="totalFiltered")
    team_podcasts: list[GetTeamPodcastsResponseTeamPodcastsItem] = Field(alias="teamPodcasts")


class AddPodcastToTeamResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    team_podcast: GetTeamPodcastsResponseTeamPodcastsItem = Field(alias="teamPodcast")


class RemoveMultiplePodcastsFromTeamResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    not_found_apple_ids: list[float] = Field(alias="notFoundAppleIds")
    errors: float
    removed_podcasts: float = Field(alias="removedPodcasts")
    not_on_list: float = Field(alias="notOnList")


class GetCurrentResponseFeatureFlags(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    s3_integration: bool | None = Field(default=None, alias="s3Integration")
    airtable_integration: bool | None = Field(default=None, alias="airtableIntegration")
    automated_search: bool | None = Field(default=None, alias="automatedSearch")
    apply_page: bool | None = Field(default=None, alias="applyPage")
    go_high_level_integration: bool | None = Field(default=None, alias="goHighLevelIntegration")


class GetCurrentResponseAliasesItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    alias: Literal[
        "deepResearchRequests",
        "diarizationRequests",
        "episodeLookups",
        "exportCount",
        "podcastLookups",
        "searchCount",
        "transcriptDownloadCount",
        "transcriptionRequests",
    ]
    label: str
    used: float
    limit: float | None


class GetCurrentResponseProjectUsageProjects(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    used: float
    limit: float | None


class GetCurrentResponseProjectUsage(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    projects: GetCurrentResponseProjectUsageProjects
    guest_profiles: GetCurrentResponseProjectUsageProjects = Field(alias="guestProfiles")


class GetCurrentResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    month: str
    plan: str
    feature_flags: GetCurrentResponseFeatureFlags = Field(alias="featureFlags")
    aliases: list[GetCurrentResponseAliasesItem]
    total_used: float = Field(alias="totalUsed")
    project_usage: GetCurrentResponseProjectUsage | None = Field(default=None, alias="projectUsage")


class GetDailyResponseDaysItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    date: str
    total_usage: float = Field(alias="totalUsage")
    usage_by_alias: dict[str, float] = Field(alias="usageByAlias")


class GetDailyResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    days: list[GetDailyResponseDaysItem]
    limits: dict[str, float | None]


class GetMonthlyResponseMonthsItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    month: str
    total_usage: float = Field(alias="totalUsage")
    usage_by_alias: dict[str, float] = Field(alias="usageByAlias")


class GetMonthlyResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    months: list[GetMonthlyResponseMonthsItem]
    limits: dict[str, float | None]


class GetMembersResponseMembersItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    user_id: str = Field(alias="userId")
    email: str | None
    display_name: str | None = Field(alias="displayName")
    total_usage: float = Field(alias="totalUsage")
    usage_by_alias: dict[str, float] = Field(alias="usageByAlias")


class GetMembersResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    members: list[GetMembersResponseMembersItem]
